config/routes.rb
require "monban/constraints/signed_in"
require "monban/constraints/signed_out"

Rails.application.routes.draw do

  constraints Monban::Constraints::SignedIn.new do
    root "dashboards#show", as: :dashboard
  end

  constraints Monban::Constraints::SignedOut.new do
    root "sessions#new"
  end

  resource :session, only: [:new, :create, :destroy]
  resources :users, only: [:new, :create, :show] do
    member do
      post "follow" => "follows#create"
      delete "follow" => "follows#destory"
    end
  end

  resources :text_shouts, only: [:create]
  resources :photo_shouts, only: [:create]
  resource :search, only: [:show]

  resources :shouts, only: [] do
    resource :like
  end

  get "/sign_up" => "users#new"
  get "/sign_in" => "sessions#new"

end

app/models/follow_relationship.rb
class FollowRelationship < ActiveRecord::Base
  belongs_to :follower, class_name: "User"
  belongs_to :followed_user, class_name: "User"

end

app/models/like.rb
class Like < ActiveRecord::Base
  belongs_to :user
  belongs_to :shout
end

app/models/photo_shout.rb
class PhotoShout < ActiveRecord::Base

  validates :url, presence: true

end

app/models/shout.rb
class Shout < ActiveRecord::Base
  belongs_to :user
  belongs_to :content, polymorphic: true

  has_many :likes

  validates :content, presence: true

  def username
    user.username
  end

  def self.text_shout_query(query)
    where(content_type: "TextShout", content_id: query)
  end

end

app/models/text_shout.rb
class TextShout < ActiveRecord::Base

  validates :body, presence: true

  def self.text_shout_search(query)
    TextShout.where("body ILIKE ?", "%#{query}%")
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :shouts

  has_many :likes
  has_many :liked_shouts, through: :likes, source: :shout

  has_many :following_relationships, foreign_key: :follower_id, class_name: "FollowRelationship"
  has_many :followed_users, through: :following_relationships

  has_many :followed_relationships, foreign_key: :followed_user_id, class_name: "FollowRelationship"
  has_many :followers, through: :followed_relationships

  validates :email, presence: true, uniqueness: true
  validates :password_digest, presence: true
  validates :username, presence: true, uniqueness: true

  def to_param
    username
  end

  def follow(user)
    followed_users << user
  end

  def unfollow(user)
    followed_users.destroy(user)
  end

  def show
    @user = User.find_by(username: params[:id])
    @shouts = @user.shouts
  end

  def timeline
    Shout.where(user_id: timeline_author_ids).order(created_at: :desc)
  end

  def self.user_query(query)
    where("username ILIKE ?", "%#{query}%")
  end

  private

  def timeline_author_ids
    [id] + followed_user_ids
  end
 
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Monban::ControllerHelpers
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/dashboards_controller.rb
class DashboardsController < ApplicationController

  def show
    @text_shout = TextShout.new
    @photo_shout = PhotoShout.new
    @shouts = current_user.timeline.page(params[:page])
  end
end

app/controllers/follows_controller.rb
class FollowsController < ApplicationController

  def create
    @user = User.find_by(username: params[:id])
    current_user.follow(@user)

    flash[:notice] = "You are now following #{@user.username}"

    redirect_to @user
  end

  def destory
    @user = User.find_by(username: params[:id])
    current_user.unfollow(@user)

    flash[:notice] = "You are no longer following #{@user.username}"

    redirect_to @user
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController

  def create
    @shout = current_shout
    current_user.liked_shouts << @shout

    redirect_to :back
  end

  def destroy
    @shout = current_shout
    current_user.liked_shouts.delete(@shout)

    redirect_to :back
  end

  private

  def current_shout
    Shout.find(params[:shout_id])
  end
end

app/controllers/photo_shouts_controller.rb
class PhotoShoutsController < ApplicationController

  def create
    @photo_shout = PhotoShout.new(photo_shout_params)
    shout = current_user.shouts.new(content: @photo_shout)

    if shout.save
      redirect_to dashboard_path
    else
      render :new
    end
  end

  private

  def photo_shout_params
    params.require(:photo_shout).permit(:url)
  end
end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController

  def show
    @shout_results = Shout.text_shout_query(text_shout_search_ids)
    @user_results = User.user_query(params[:query])
  end

  private

  def text_shout_search_ids
    TextShout.text_shout_search(params[:query]).pluck(:id)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :require_login, only: [:new, :create]

  def new
  end

  def create
    user = authenticate_session(session_params)

    if sign_in(user)
      redirect_to root_path
    else
      render :new
    end
  end

  def destroy
    sign_out
    redirect_to root_path
  end

  private

  def session_params
    params.require(:session).permit(:username, :password)
  end
end

app/controllers/text_shouts_controller.rb
class TextShoutsController < ApplicationController
  before_action :require_login

  def new
    @shout = Shout.new
  end

  def create
    @text_shout = TextShout.new(text_shout_params)

    if @text_shout.save
      current_user.shouts.create(content: @text_shout)
      flash[:notice] = "Shout created!"
      redirect_to dashboard_path
    else
      render "dashboards/show"
    end
  end

  private

  def text_shout_params
    params.require(:text_shout).permit(:body)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :require_login, only: [:new, :create]

  def new
    @user = User.new
  end

  def create
    @user = sign_up(user_params)

    if @user.valid?
      sign_in(@user)
      redirect_to root_path
    else
      render :new
    end
  end

  def show
    @user = User.find_by(username: params[:id])
    @shouts = @user.shouts.order(created_at: :desc).page(params[:page])
  end

  private

  def user_params
    params.require(:user).permit(:username, :email, :password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/application/_error_messages.html.erb
<% if errors.any? %>
  <div>
    <p>We could not save because: </p>
    <ul><% errors.full_messages.each do |error_message| %>
      <li><%= error_message %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/dashboards/show.html.erb
<h1><%= current_user.username %>'s Dashboard</h1>

<section>
  <h3>Create Text Shout</h3>
  <fieldset style="width: 400px">
  <%= form_for @text_shout do |form| %>
    <div>
      <%= form.label :body, "Text: " %>
      <%= form.text_field :body %>
      <%= form.submit "New Text Shout" %>
    </div>
  <% end %>
  </fieldset>
</section>

<section>
  <h3>Create Photo Shout</h3>
  <fieldset style="width: 400px">
  <%= form_for @photo_shout do |form| %>
    <div>
      <%= form.label :url, "url: " %>
      <%= form.text_field :url %>
      <%= form.submit "New Photo Shout" %>
    </div>
  <% end %>
  </fieldset>
</section>


<h2>Your Timeline</h2>
<div>
  <%= render @shouts %>
</div>

<%= paginate @shouts %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Shoutr</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <% if signed_in? %>
    <p><b>You are signed in as: <%= link_to current_user.username, user_path(current_user) %> | | </b>
    <%= link_to "Sign out", session_path, method: :delete %></p>
    <fieldset style="width: 400px">
      <b>Search: </b>
      <%= form_tag search_path, method: :get do %>
        <%= search_field_tag :query, params[:query], placeholder: "Search" %>
        <%= submit_tag "Search" %>
      <% end %>
    </fieldset>
  <% else %>
    <p><%= link_to "Sign in", sign_in_path %>
  - or - 
  <%= link_to "Sign up", sign_up_path %></p>
  <% end %>

  <div>
    <p>
    <% flash.each do |name, message| %>
      <%= content_tag :div, message, class: name %>
    <% end %>
    </p>
  </div>

<%= yield %>

</body>
</html>

app/views/photo_shouts/_photo_shout.html.erb
<%= image_tag photo_shout.url, width: "200" %>

app/views/searches/show.html.erb
<h1>Search Results for "<%= params[:query] %>"</h1>

<section>
  <h3>Shout Results:</h3>
  <% if @shout_results.present? %>
    <%= render @shout_results %>
  <% else %>
    <p>No Shouts matched your search</p>
  <% end %>
</section>

<hr>

<section>
  <h3>User Results:</h3>
  <% if @user_results.present? %>
    <%= render @user_results %>
  <% else %>
    <p>No Users matched your search</p>
  <% end %>
</section>

app/views/shouts/_form.html.erb
<div>
  <%= form_for shout do |form| %>
    <div>
      <%= form.label :content %>
      <%= form.text_area :content %>
    </div>
    <div>
      <%= form.submit %>
    </div>
  <% end %>
</div>

app/views/shouts/_shout.html.erb
<div>
  <p><b><i><%= render shout.content %></i></b></p>
  <p>
    -- Shouted by: <%= link_to shout.username, shout.user %>
    - - Shouted <%= time_ago_in_words(shout.created_at) %> ago
  </p>

  <% unless current_user == shout.user %>
    <% if current_user.liked_shouts.include?(shout) %>
      <%= button_to "Unlike", shout_like_path(shout), method: :delete %>
      <%= pluralize(shout.likes.count, "like") %>
    <% else %>
      <%= button_to "Like", shout_like_path(shout) %>
    <% end %>
  <% end %>

</div>

<hr>

app/views/shouts/new.html.erb
<h1>Create New Shout</h1>

<%= render "application/error_messages", errors: @shout.errors %>

<%= render "form", shout: @shout %>

app/views/text_shouts/_text_shout.html.erb
<%= text_shout.body %>

app/views/users/_user.html.erb
<div>
  <p> User: <%= link_to user.username %></p>
  <!-- <p> &#45;&#45; <%= user.followers.count %> <%="follower".pluralize(user.followers.count) %></p> -->
  <p> -- <%= pluralize(user.followers.count, "follower") %></p>
</div>

app/views/users/new.html.erb
<%= form_for @user do |form| %>

  <% if @user.errors.any? %>
    <%= pluralize(@user.errors.count, "error") %> prevented your account from being created:
    <ul>
      <% @user.errors.full_messages.each do |error_message| %>
        <li><%= error_message %></li>
      <% end %>
    </ul>
  <% end %>

  <div>
    <%= form.label :username %>
    <%= form.text_field :username %>
  </div>
  <div>
    <%= form.label :email %>
    <%= form.email_field :email %>
  </div>
  <div>
    <%= form.label :password %>
    <%= form.password_field :password %>
  </div>
  <div>
    <%= form.submit "Sign up" %>
  </div>
<% end %>

app/views/users/show.html.erb
<header>
<h2><%= @user.username %>'s Profile</h2>
<% if @user == current_user %>
  <p>Welcome to your profile!</p>
<% else %>
  <% if @user.followers.include? current_user %>
    <%= button_to "Unfollow #{@user.username}", follow_user_path(@user), method: :delete %>
  <% else %>
    <%= button_to "Follow #{@user.username}", follow_user_path(@user) %>
  <% end %>
<% end %>

<p><i><%= @user.username %> has <%= pluralize(@user.followers.count, "follower") %></i></p>
<p><i><%= @user.username %> is following <%= pluralize(@user.followed_users.count, "user") %></i></p>
</header>

<br>

<section>
  <h2><%= @user.username %>'s Shouts</h2>
  <%= render @shouts %>
</section>

<%= paginate @shouts %>